services:
  tavilyhikari:
    image: ghcr.io/ivanli-cn/tavily-hikari:latest
    container_name: tavilyhikari
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8787:8787"
    volumes:
      - ./data:/srv/app/data
    networks:
      - tavilyhikari
      - apinetwork

networks:
  tavilyhikari:
    name: tavilyhikari
  apinetwork:
    name: apinetwork
